/**
 * The game's shared colour palette.
 *
 * GENERATED by scripts/build-palette.mjs — do not edit by hand. It is clustered
 * from the shipped art so that canvas-drawn pixels (particles, outlines, text,
 * UI) sit in the same colour space as the sprites.
 */
export const PALETTE = [
  '#412313',
  '#ae4a14',
  '#f8dbca',
  '#cf7a43',
  '#864e26',
  '#693a16',
  '#f19a51',
  '#937354',
  '#e9b37c',
  '#ad6f26',
  '#ec870d',
  '#d8c4aa',
  '#dda83b',
  '#fed859',
  '#fbf8ed',
  '#f4c708',
  '#a5a6a1',
  '#a4ca22',
  '#424340',
  '#76d504',
  '#3f9413',
  '#0c540f',
  '#707a72',
  '#85958d',
  '#525957',
  '#91ece5',
  '#2bc9df',
  '#23839e',
  '#262f33',
  '#184862',
  '#141e26',
  '#0e0d12',
] as const;

export type PaletteColour = (typeof PALETTE)[number];

/** Darkest and lightest entries, for outlines and highlights. */
export const INK = '#0e0d12';
export const HIGHLIGHT = '#fed859';

/** Nearest palette entry to an arbitrary colour. */
export function quantise(r: number, g: number, b: number): string {
  let best: string = PALETTE[0];
  let bd = Infinity;
  for (const p of PALETTE) {
    const pr = parseInt(p.slice(1, 3), 16);
    const pg = parseInt(p.slice(3, 5), 16);
    const pb = parseInt(p.slice(5, 7), 16);
    const d = (pr - r) ** 2 + (pg - g) ** 2 + (pb - b) ** 2;
    if (d < bd) { bd = d; best = p; }
  }
  return best;
}
