/**
 * The game's shared colour palette.
 *
 * GENERATED by scripts/build-palette.mjs — do not edit by hand. It is clustered
 * from the shipped art so that canvas-drawn pixels (particles, outlines, text,
 * UI) sit in the same colour space as the sprites.
 */
export const PALETTE = [
  '#facac2',
  '#e29372',
  '#412112',
  '#fbb18c',
  '#ce7545',
  '#8e4219',
  '#eb944c',
  '#b6631d',
  '#613f21',
  '#f5a053',
  '#916233',
  '#e7b57a',
  '#ee8f0c',
  '#b2a89a',
  '#d0c7b8',
  '#d9c39b',
  '#f9edd3',
  '#dcae38',
  '#fed859',
  '#f9d507',
  '#a5ca23',
  '#6e9921',
  '#85de04',
  '#50bc04',
  '#327915',
  '#f4faf3',
  '#727971',
  '#09500e',
  '#9ea2a0',
  '#3ed5d7',
  '#1e2629',
  '#3b4b52',
] as const;

export type PaletteColour = (typeof PALETTE)[number];

/** Darkest and lightest entries, for outlines and highlights. */
export const INK = '#1e2629';
export const HIGHLIGHT = '#fed859';

/** Nearest palette entry to an arbitrary colour. */
export function quantise(r: number, g: number, b: number): string {
  let best: string = PALETTE[0];
  let bd = Infinity;
  for (const p of PALETTE) {
    const pr = parseInt(p.slice(1, 3), 16);
    const pg = parseInt(p.slice(3, 5), 16);
    const pb = parseInt(p.slice(5, 7), 16);
    const d = (pr - r) ** 2 + (pg - g) ** 2 + (pb - b) ** 2;
    if (d < bd) { bd = d; best = p; }
  }
  return best;
}
