/**
 * The game's shared colour palette.
 *
 * GENERATED by scripts/build-palette.mjs — do not edit by hand. It is clustered
 * from the shipped art so that canvas-drawn pixels (particles, outlines, text,
 * UI) sit in the same colour space as the sprites.
 */
export const PALETTE = [
  '#35170c',
  '#f3cdbb',
  '#552d14',
  '#ce7a42',
  '#99501f',
  '#6b4122',
  '#f19b50',
  '#e8b37d',
  '#e77d0f',
  '#382b1d',
  '#a47839',
  '#fdfbf8',
  '#daa73f',
  '#fdd35b',
  '#f5eed8',
  '#f6c00b',
  '#5b5951',
  '#c2c3b5',
  '#a2a39d',
  '#9fc50b',
  '#a3d329',
  '#414240',
  '#5db510',
  '#338018',
  '#777e75',
  '#0b510f',
  '#86dcd8',
  '#29b4ca',
  '#1c5c71',
  '#121c22',
  '#222d37',
  '#0d090c',
] as const;

export type PaletteColour = (typeof PALETTE)[number];

/** Darkest and lightest entries, for outlines and highlights. */
export const INK = '#0d090c';
export const HIGHLIGHT = '#fdd35b';

/** Nearest palette entry to an arbitrary colour. */
export function quantise(r: number, g: number, b: number): string {
  let best: string = PALETTE[0];
  let bd = Infinity;
  for (const p of PALETTE) {
    const pr = parseInt(p.slice(1, 3), 16);
    const pg = parseInt(p.slice(3, 5), 16);
    const pb = parseInt(p.slice(5, 7), 16);
    const d = (pr - r) ** 2 + (pg - g) ** 2 + (pb - b) ** 2;
    if (d < bd) { bd = d; best = p; }
  }
  return best;
}
