#!/usr/bin/env node
/**
 * build-palette.mjs — derive one shared colour palette from the generated art.
 *
 * A palette invented up front would fight the art; this samples what the
 * generator actually produced and clusters it, so the palette describes the game
 * that exists. It is written to src/game/render/palette.ts and used for UI,
 * particles, outlines and text, giving canvas-drawn and generated pixels the
 * same colours.
 *
 * Usage: node scripts/build-palette.mjs [k]
 */
import { readdirSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { loadRGBA, removeChromaBackground, rgbToHsv } from './lib/image.mjs';

const K = Number(process.argv[2] || 32);
const DIRS = ['terrain', 'world', 'items', 'characters', 'ui'].map((d) => join('assets-src', d));

/** Collect opaque, non-background pixels from every asset. */
const samples = [];
for (const dir of DIRS) {
  let files;
  try { files = readdirSync(dir).filter((f) => f.endsWith('.png')); } catch { continue; }
  for (const f of files) {
    const raw = await loadRGBA(join(dir, f));
    const cleaned = dir.endsWith('terrain') ? raw : removeChromaBackground(raw);
    const { data, width, height } = cleaned;
    const step = Math.max(1, Math.floor((width * height) / 1200));
    for (let p = 0; p < width * height; p += step) {
      const i = p * 4;
      if (data[i + 3] < 200) continue;
      samples.push([data[i], data[i + 1], data[i + 2]]);
    }
  }
}
console.log(`sampled ${samples.length} pixels`);

// k-means++ style seeding, then Lloyd iterations. Deterministic: fixed stride
// seeding and a fixed iteration count, so the palette is reproducible.
const centroids = [];
const stride = Math.floor(samples.length / K) || 1;
for (let i = 0; i < K; i++) centroids.push([...samples[(i * stride) % samples.length]]);

const dist2 = (a, b) => (a[0]-b[0])**2 + (a[1]-b[1])**2 + (a[2]-b[2])**2;

for (let iter = 0; iter < 24; iter++) {
  const sums = Array.from({ length: K }, () => [0, 0, 0, 0]);
  for (const s of samples) {
    let best = 0, bd = Infinity;
    for (let c = 0; c < K; c++) {
      const d = dist2(s, centroids[c]);
      if (d < bd) { bd = d; best = c; }
    }
    sums[best][0] += s[0]; sums[best][1] += s[1]; sums[best][2] += s[2]; sums[best][3] += 1;
  }
  for (let c = 0; c < K; c++) {
    if (sums[c][3] === 0) continue;
    centroids[c] = [
      Math.round(sums[c][0] / sums[c][3]),
      Math.round(sums[c][1] / sums[c][3]),
      Math.round(sums[c][2] / sums[c][3]),
    ];
  }
}

// Order by hue then value so the generated file reads as a designed ramp.
centroids.sort((a, b) => {
  const ha = rgbToHsv(...a), hb = rgbToHsv(...b);
  return ha.h - hb.h || ha.v - hb.v;
});

const hex = (c) => '#' + c.map((v) => Math.max(0, Math.min(255, v)).toString(16).padStart(2, '0')).join('');
const byVal = [...centroids].sort((a, b) => rgbToHsv(...a).v - rgbToHsv(...b).v);

mkdirSync('src/game/render', { recursive: true });
writeFileSync('src/game/render/palette.ts', `/**
 * The game's shared colour palette.
 *
 * GENERATED by scripts/build-palette.mjs — do not edit by hand. It is clustered
 * from the shipped art so that canvas-drawn pixels (particles, outlines, text,
 * UI) sit in the same colour space as the sprites.
 */
export const PALETTE = [
${centroids.map((c) => `  '${hex(c)}',`).join('\n')}
] as const;

export type PaletteColour = (typeof PALETTE)[number];

/** Darkest and lightest entries, for outlines and highlights. */
export const INK = '${hex(byVal[0])}';
export const HIGHLIGHT = '${hex(byVal[byVal.length - 1])}';

/** Nearest palette entry to an arbitrary colour. */
export function quantise(r: number, g: number, b: number): string {
  let best = PALETTE[0];
  let bd = Infinity;
  for (const p of PALETTE) {
    const pr = parseInt(p.slice(1, 3), 16);
    const pg = parseInt(p.slice(3, 5), 16);
    const pb = parseInt(p.slice(5, 7), 16);
    const d = (pr - r) ** 2 + (pg - g) ** 2 + (pb - b) ** 2;
    if (d < bd) { bd = d; best = p; }
  }
  return best;
}
`);
writeFileSync('docs/palette.json', JSON.stringify(centroids.map(hex), null, 2));
console.log(`wrote src/game/render/palette.ts (${K} colours)`);
console.log('ink:', hex(byVal[0]), 'highlight:', hex(byVal[byVal.length - 1]));
